### ISSUE TITLE
Ajax with the new version of simple_calendar

### ISSUE THREAD

**Issue by chrisokamoto** [excid3/simple_calendar-ajax-example#1]
Hello,

I'm trying to make the new version of simple_calendar working with ajax.
I saw here that you coded this in helper:

```
def events_ajax_previous_link
    ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
  end

  def events_ajax_next_link
    ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
  end
```

You submitted this code 2 years ago.. This is'n't working with the new version of simple_calendar (2.0.6) and I wanted to use this version because of the styles of CSS I already have coded.. With this version, I can't create a remote link nor change the name of "Previous" and "Next" links, like the methods events_ajax_previous_link and events_ajax_next_link does. I tried to downgrade the version of simple_calendar just for testing this code and it worked perfectly...

What should I do to have ajax links with the new version?

**Comment by excid3** [comment]
The new one should be even easier since you're able to override the views in your app. You'll want to generate those views and take the same approach. I can update this example tonight for you!

**Comment by chrisokamoto** [comment]
Ok, thank you very much!! I'm gonna try overriding the view.. :)

**Comment by chrisokamoto** [comment]
I got it working !! So much simple!! thank you!

**Comment by excid3** [comment]
Awesome! We just got the example updated as well. Thanks to @king601 for that! :+1:
