### ISSUE TITLE
Bugs in rails 5

### ISSUE THREAD

**Issue by ariawanzero** [excid3/simple_calendar-ajax-example#4]
I'm trying use this ajax on my project but my page still refresh. i already follow all your code but not working in my project. can you give another example or clue in rails 5

**Comment by RailsCod3rFuture** [comment]
I'm getting page redirects when you click previous view and next view. I'm using the AJAX approach. Has anyone figured this out for Rails 5?

<%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>

**Comment by excid3** [comment]
The repo has been updated to Rails 5.1 and the latest simple_calendar. Everything is still working as before. 👍
