### ISSUE TITLE
I'm getting "undefined method `reject' for nil:NilClass"

### ISSUE THREAD

**Issue by RailsCod3rFuture** [excid3/simple_calendar-ajax-example#5]
For some reason, the method reject is being called in the _calendar.html.erb partial and I can't load the page because of it. Have you see this error before?

```
<%= month_calendar events: @meetings do |date, meetings| %>
    <%= date.day %>
    <% meetings.each do |meeting| %>
        "<strong style="font-size: 0.80em"><%= truncate(meeting.name, length: 40) %></strong>"
    <% end %>
<% end %>

```

**Comment by excid3** [comment]
Looks like your `@meetings` was nil and not set in the controller. This code base uses `@events` and not `@meetings` so you may want to inspect your changes.

**Comment by RailsCod3rFuture** [comment]
Thanks.
